### ISSUE TITLE
Documentation clarification...

### ISSUE THREAD

**Issue by MichaelTiernan** [snabb/downtimed#2]
If I change the sleep time on startup for 'downtimed' do I have to tell downtimes of this change for proper reporting?

When I do a 'downtimed -v', I get the default values it uses but is there a way to query the currently running instance?

Lastly, if I change the time format on downtimed do I have to tell downtimes the same thing?

Just trying to get a reality check here.

**Comment by snabb** [comment]
1) Yes, to improve reporting estimation in case there are crashes (there is no difference in case of graceful shutdown). The sleep time in use is not recorded in the data file.

2) No.

3) No. downtimed (daemon) time format setting has effect on logging only.
