### ISSUE TITLE
time sync feature?

### ISSUE THREAD

**Issue by anonproject** [snabb/downtimed#7]
Unfortunately the program doesn't work in case if the system time has been changed during restart.

I wonder how it can be fixed.  For example if I would make something like this:

```text
/etc/systemd/system/downtimed.service.d/override.conf
[Service]
ExecStartPre=-/usr/sbin/ntpdate -u pool.ntp.org
```
And then:
```text
[Unit]
After=network-online.target
Wants=network-online.target
```

Right?

**Comment by snabb** [comment]
Yes. To be able to calculate time difference, one needs to know time. Normally time synchronization is configured in a separate unit file.
